# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title dummy cpp-function
#' @name hello_cpp
#' @param int_ an integer
#' @return /
#' @export
hello_cpp <- function(number) {
    invisible(.Call(`_duflor_install_test_hello_cpp`, number))
}

